### PR TITLE
Replace deprecated filter property calls

### LINKED ISSUE #7: filterProperty is deprecated in favour of filterBy
The docs have been updated to reflect this (see https://github.com/emberjs/website/pull/882) but the example code still uses the old version.

Specifically, within the todos controller the  `clearCompleted` action and the `completed` and `remaining` properties use the deprecated method.

### PR DESCRIPTION
**Pull request by davefp**
Fixes #7

You'll have to force the merge as I've done a rebase to update the old commits. Hope that's ok!

### CODE REVIEW

**Comment by trek** [comment]
Unfortunately there's additional process around changes to this repo: specifically creating new JSBins and updating the JSBin links on the website. We can't merge until there's also a PR for that :-/

**Comment by davefp** [comment]
Hmm, tricky. If I create the new JSBins and open an accompanying PR on the site repo, will you merge both or do you require someone in particular to do that?

**Comment by trek** [comment]
I can merge both.

**Comment by davefp** [comment]
Closing due to old age :)

**Pull request closed without merging**
